#pragma once

#include "driver/gpio.h"
#include "esp_adc/adc_oneshot.h"

#define LANTERN_BOARD_ID "lantern-original"
#define LANTERN_MODEL "ZHENGCHEN-1.54-M1307"
#define LANTERN_STORAGE_KIND "psram-stream"

#define LANTERN_HAS_SD_CARD 0
#define LANTERN_HAS_TOUCHSCREEN 0
#define LANTERN_HAS_PHYSICAL_BUTTONS 1
#define LANTERN_HAS_BATTERY_MONITOR 1
#define LANTERN_BATTERY_INSTALLED 1
#define LANTERN_HAS_POWER_HOLD 1
#define LANTERN_HAS_CHARGING_SIGNAL 1

#define LANTERN_DISPLAY_DRIVER_ST7789 1
#define LANTERN_DISPLAY_DRIVER_ILI9341 0
#define LANTERN_AUDIO_CODEC_ES8311 0
#define LANTERN_AUDIO_SHARED_BUS 0

#define LANTERN_POWER_HOLD_GPIO GPIO_NUM_2
#define LANTERN_CHARGING_GPIO GPIO_NUM_9

#define LANTERN_BUTTON_MAIN_GPIO GPIO_NUM_0
#define LANTERN_BUTTON_UP_GPIO GPIO_NUM_10
#define LANTERN_BUTTON_DOWN_GPIO GPIO_NUM_39

#define LANTERN_MIC_WS_GPIO GPIO_NUM_4
#define LANTERN_MIC_SCK_GPIO GPIO_NUM_5
#define LANTERN_MIC_DATA_GPIO GPIO_NUM_6
#define LANTERN_MIC_SAMPLE_RATE 16000

#define LANTERN_SPK_DATA_GPIO GPIO_NUM_7
#define LANTERN_SPK_BCLK_GPIO GPIO_NUM_15
#define LANTERN_SPK_LRCK_GPIO GPIO_NUM_16
#define LANTERN_SPK_SAMPLE_RATE 24000
#define LANTERN_TTS_SAMPLE_RATE 24000

#define LANTERN_DISPLAY_MOSI_GPIO GPIO_NUM_41
#define LANTERN_DISPLAY_MISO_GPIO GPIO_NUM_NC
#define LANTERN_DISPLAY_SCLK_GPIO GPIO_NUM_42
#define LANTERN_DISPLAY_RESET_GPIO GPIO_NUM_45
#define LANTERN_DISPLAY_DC_GPIO GPIO_NUM_40
#define LANTERN_DISPLAY_CS_GPIO GPIO_NUM_21
#define LANTERN_DISPLAY_BACKLIGHT_GPIO GPIO_NUM_20
#define LANTERN_DISPLAY_WIDTH 240
#define LANTERN_DISPLAY_HEIGHT 240

#define LANTERN_BATTERY_ADC_CHANNEL ADC_CHANNEL_7

#define LANTERN_SETUP_AP_PASSWORD "lanternsetup"
