#pragma once

#include "driver/gpio.h"
#include "esp_adc/adc_oneshot.h"

#define LANTERN_BOARD_ID "lantern-v2"
#define LANTERN_MODEL "LCDWIKI-ES3C28P"
#define LANTERN_STORAGE_KIND "sdmmc+psram-retry"

#define LANTERN_HAS_SD_CARD 1
#define LANTERN_HAS_TOUCHSCREEN 1
#define LANTERN_HAS_PHYSICAL_BUTTONS 0
#define LANTERN_HAS_BATTERY_MONITOR 1
#define LANTERN_BATTERY_INSTALLED 1
#define LANTERN_HAS_POWER_HOLD 0
#define LANTERN_HAS_CHARGING_SIGNAL 0
#define LANTERN_HAS_USB_CHARGE_DETECT 1
#define LANTERN_CHARGING_ACTIVE_LEVEL 0

#define LANTERN_DISPLAY_DRIVER_ST7789 0
#define LANTERN_DISPLAY_DRIVER_ILI9341 1
#define LANTERN_AUDIO_CODEC_ES8311 1
#define LANTERN_AUDIO_SHARED_BUS 1

#define LANTERN_POWER_HOLD_GPIO GPIO_NUM_NC
#define LANTERN_CHARGING_GPIO GPIO_NUM_NC

// The board exposes BOOT and RESET for development, but product controls use
// the capacitive screen.
#define LANTERN_BUTTON_MAIN_GPIO GPIO_NUM_0
#define LANTERN_BUTTON_UP_GPIO GPIO_NUM_NC
#define LANTERN_BUTTON_DOWN_GPIO GPIO_NUM_NC

#define LANTERN_MIC_WS_GPIO GPIO_NUM_7
#define LANTERN_MIC_SCK_GPIO GPIO_NUM_5
#define LANTERN_MIC_DATA_GPIO GPIO_NUM_6
#define LANTERN_MIC_MCLK_GPIO GPIO_NUM_4
#define LANTERN_MIC_SAMPLE_RATE 16000

#define LANTERN_SPK_DATA_GPIO GPIO_NUM_8
#define LANTERN_SPK_BCLK_GPIO GPIO_NUM_5
#define LANTERN_SPK_LRCK_GPIO GPIO_NUM_7
#define LANTERN_SPK_MCLK_GPIO GPIO_NUM_4
#define LANTERN_SPK_SAMPLE_RATE 16000
#define LANTERN_TTS_SAMPLE_RATE 24000

#define LANTERN_AUDIO_AMP_ENABLE_GPIO GPIO_NUM_1
#define LANTERN_I2C_SDA_GPIO GPIO_NUM_16
#define LANTERN_I2C_SCL_GPIO GPIO_NUM_15
#define LANTERN_ES8311_I2C_ADDRESS 0x18

#define LANTERN_TOUCH_RESET_GPIO GPIO_NUM_18
#define LANTERN_TOUCH_INTERRUPT_GPIO GPIO_NUM_17
#define LANTERN_TOUCH_I2C_ADDRESS 0x38

#define LANTERN_DISPLAY_MOSI_GPIO GPIO_NUM_11
#define LANTERN_DISPLAY_MISO_GPIO GPIO_NUM_13
#define LANTERN_DISPLAY_SCLK_GPIO GPIO_NUM_12
#define LANTERN_DISPLAY_RESET_GPIO GPIO_NUM_NC
#define LANTERN_DISPLAY_DC_GPIO GPIO_NUM_46
#define LANTERN_DISPLAY_CS_GPIO GPIO_NUM_10
#define LANTERN_DISPLAY_BACKLIGHT_GPIO GPIO_NUM_45
#define LANTERN_DISPLAY_WIDTH 240
#define LANTERN_DISPLAY_HEIGHT 320

#define LANTERN_SD_CLK_GPIO GPIO_NUM_38
#define LANTERN_SD_CMD_GPIO GPIO_NUM_40
#define LANTERN_SD_D0_GPIO GPIO_NUM_39
#define LANTERN_SD_D1_GPIO GPIO_NUM_41
#define LANTERN_SD_D2_GPIO GPIO_NUM_48
#define LANTERN_SD_D3_GPIO GPIO_NUM_47

#define LANTERN_BATTERY_ADC_CHANNEL ADC_CHANNEL_8
#define LANTERN_BATTERY_CAPACITY_MAH 4000
#define LANTERN_CHARGE_CURRENT_MA 290

#define LANTERN_SETUP_AP_PASSWORD "lanternsetup"
